# Generated by Django 2.1.2 on 2018-11-29 16:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('aptman', '0002_auto_20181128_1938'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apartment',
            name='tenant_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='aptman.Tenant'),
        ),
        migrations.AlterField(
            model_name='tenant',
            name='last_payment',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='tenant',
            name='missed_payments',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='tenant',
            name='next_payment',
            field=models.CharField(max_length=10),
        ),
    ]
