# Generated by Django 2.1.2 on 2018-11-28 17:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Apartments',
            fields=[
                ('apt_id', models.IntegerField(primary_key=True, serialize=False)),
                ('apt_complex', models.CharField(max_length=200)),
                ('monthly_rent', models.DecimalField(decimal_places=2, max_digits=25)),
                ('vacant', models.BooleanField(default=True)),
                ('tenant', models.CharField(default=None, max_length=200)),
                ('maintenance_needed', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='PaymentHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_date', models.DateField()),
                ('payment_amount', models.DecimalField(decimal_places=2, max_digits=25)),
            ],
        ),
        migrations.CreateModel(
            name='Tenants',
            fields=[
                ('tenant_id', models.IntegerField(primary_key=True, serialize=False)),
                ('last_payment', models.DateField()),
                ('next_payment', models.DateField()),
                ('expected_payment', models.DecimalField(decimal_places=2, max_digits=25)),
                ('missed_payments', models.IntegerField()),
                ('apt_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aptman.Apartments')),
            ],
        ),
        migrations.AddField(
            model_name='paymenthistory',
            name='tenant_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aptman.Tenants'),
        ),
    ]
