# Generated by Django 2.1.2 on 2018-11-29 01:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('aptman', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apartment',
            name='tenant_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='aptman.Tenant'),
        ),
        migrations.AlterField(
            model_name='tenant',
            name='apt_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='aptman.Apartment'),
        ),
    ]
